GameLibrary/Controllers/AppController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameLibrary.Data;
using GameLibrary.Data.Entities;
using GameLibrary.Services;
using GameLibrary.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GameLibrary.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        private readonly GameContext _context;
        private readonly UserManager<StoreUser> userManager;

        public AppController(IMailService mailService, GameContext context,UserManager<StoreUser> userManager)
        {
            _mailService = mailService;
            _context = context;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            //StoreUser user = await userManager.FindByEmailAsync("nikunj@rathod.com");

            //if (user == null)
            //{
            //    user = new StoreUser()
            //    {
            //        FirstName = "Nikunj",
            //        LastName = "Rathod",
            //        Email = "nikunj@rathod.com",
            //        UserName = "nikunj3011"
            //    };

            //    var result = await userManager.CreateAsync(user, "P@ssw0rd!");
            //    if (result != IdentityResult.Success)
            //    {
            //        throw new InvalidOperationException("Could not create new user in Seeder");
            //    }
            //}
            //throw new InvalidOperationException();
            return View();
        }

        [HttpGet("about")]
        public IActionResult AboutUs()
        {
            ViewBag.Title = "About Us";
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Contact Us";

            //throw new InvalidOperationException("404");
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                //send email
                //_mailService.SendMessage("a@a.com", model.Name, $"from: { model.Email} , Message: {model.message}");
                ViewBag.UserMessage = "Sent mail";
                ModelState.Clear();
            }
            else
            {
                //show errors
            }
            return View();
        }

        [Authorize]
        public IActionResult Shop()
        {
            var results = from p in _context.GameLibraries
                          orderby p.Name
                          select p; //linq syntax


            //var results =_context.GameLibraries.OrderBy(p=>p.Name).ToList();  //fluid syntax we can do either
            return View(results.ToList()); 
        }
    }
}

GameLibrary/Controllers/GameShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameLibrary.Data;
using GameLibrary.Data.Entities;

namespace GameLibrary.Controllers
{
    public class GameShopsController : Controller
    {
        private readonly GameContext _context;

        public GameShopsController(GameContext context)
        {
            _context = context;
        }

        // GET: GameShops
        public async Task<IActionResult> Index()
        {
            var gameContext = _context.GameShops.Include(g => g.GameLibrary).Include(g => g.GameSystem);
            return View(await gameContext.ToListAsync());
        }

        // GET: GameShops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameShop = await _context.GameShops
                .Include(g => g.GameLibrary)
                .Include(g => g.GameSystem)
                .FirstOrDefaultAsync(m => m.GameShopID == id);
            if (gameShop == null)
            {
                return NotFound();
            }

            return View(gameShop);
        }

        // GET: GameShops/Create
        public IActionResult Create()
        {
            ViewData["GameLibraryID"] = new SelectList(_context.GameLibraries, "GameLibraryID", "Name");
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName");
            return View();
        }

        // POST: GameShops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameShopID,GameShopName,Description,GameLibraryID,GameSystemID,Address,CreationDate")] GameShop gameShop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gameShop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameLibraryID"] = new SelectList(_context.GameLibraries, "GameLibraryID", "Name", gameShop.GameLibraryID);
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", gameShop.GameSystemID);
            return View(gameShop);
        }

        // GET: GameShops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameShop = await _context.GameShops.FindAsync(id);
            if (gameShop == null)
            {
                return NotFound();
            }
            ViewData["GameLibraryID"] = new SelectList(_context.GameLibraries, "GameLibraryID", "Name", gameShop.GameLibraryID);
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", gameShop.GameSystemID);
            return View(gameShop);
        }

        // POST: GameShops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameShopID,GameShopName,Description,GameLibraryID,GameSystemID,Address,CreationDate")] GameShop gameShop)
        {
            if (id != gameShop.GameShopID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gameShop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameShopExists(gameShop.GameShopID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameLibraryID"] = new SelectList(_context.GameLibraries, "GameLibraryID", "Name", gameShop.GameLibraryID);
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", gameShop.GameSystemID);
            return View(gameShop);
        }

        // GET: GameShops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameShop = await _context.GameShops
                .Include(g => g.GameLibrary)
                .Include(g => g.GameSystem)
                .FirstOrDefaultAsync(m => m.GameShopID == id);
            if (gameShop == null)
            {
                return NotFound();
            }

            return View(gameShop);
        }

        // POST: GameShops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gameShop = await _context.GameShops.FindAsync(id);
            _context.GameShops.Remove(gameShop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameShopExists(int id)
        {
            return _context.GameShops.Any(e => e.GameShopID == id);
        }
    }
}

GameLibrary/Controllers/LibrariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameLibrary.Data;
using GameLibrary.Data.Entities;

namespace GameLibrary.Controllers
{
    public class LibrariesController : Controller
    {
        private readonly GameContext _context;

        public LibrariesController(GameContext context)
        {
            _context = context;
        }

        // GET: Libraries
        public async Task<IActionResult> Index()
        {
            var gameContext = _context.GameLibraries.Include(l => l.GameSystems);
            return View(await gameContext.ToListAsync());
        }

        // GET: Libraries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var library = await _context.GameLibraries
                .Include(l => l.GameSystems)
                .FirstOrDefaultAsync(m => m.GameLibraryID == id);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        // GET: Libraries/Create
        public IActionResult Create()
        {
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName");
            return View();
        }

        // POST: Libraries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameLibraryID,Name,Description,GameSystemID,Rating,DiscType,CreationDate")] Library library)
        {
            if (ModelState.IsValid)
            {
                _context.Add(library);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", library.GameSystemID);
            return View(library);
        }

        // GET: Libraries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var library = await _context.GameLibraries.FindAsync(id);
            if (library == null)
            {
                return NotFound();
            }
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", library.GameSystemID);
            return View(library);
        }

        // POST: Libraries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameLibraryID,Name,Description,GameSystemID,Rating,DiscType,CreationDate")] Library library)
        {
            if (id != library.GameLibraryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(library);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibraryExists(library.GameLibraryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameSystemID"] = new SelectList(_context.GameSystems, "GameSystemID", "SystemName", library.GameSystemID);
            return View(library);
        }

        // GET: Libraries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var library = await _context.GameLibraries
                .Include(l => l.GameSystems)
                .FirstOrDefaultAsync(m => m.GameLibraryID == id);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        // POST: Libraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var library = await _context.GameLibraries.FindAsync(id);
            _context.GameLibraries.Remove(library);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibraryExists(int id)
        {
            return _context.GameLibraries.Any(e => e.GameLibraryID == id);
        }
    }
}

GameLibrary/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <title>Game Library</title>

    <!--<link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />-->
    @*<link rel="stylesheet" href="css/style.css">*@
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/dist/games.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    @RenderSection("head", false)
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand"><i class="fa fa-paint-brush"></i> Welcome to Game Library</h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="GameSystems" asp-action="Index">Game Systems</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Libraries" asp-action="Index">Game Library</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="GameShops" asp-action="Index">Game Shops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="AboutUs">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="Shop">Games</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }

                </ul>
            </div>
        </nav>
    </header>
    <br />
    @*<section class="container">
            <h2 class="text-center">@ViewBag.Title</h2>
        </section>*@
    <div class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
        <div class="row">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">

            </div>
        </div>
    </div>
    <br />
    <footer class="container">
        <div class="text-center">Copyright 2021 Game Library LLC</div>
    </footer>
    
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/solid.js"></script>
        <script src="~/js/index.js"></script>
        <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/index.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @*<script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.min.js"></script>*@
        @*<script src="~/lib/fortawesome/fontawesome-free/js/solid.min.js"></script>*@
        @*<script src="~/di/dutchtreat.min.js" asp-append-version="true"></script>*@
    </environment>
    @RenderSection("scripts", false)
</body>
</html>